### ISSUE TITLE
Can't use AWS Scalars

### ISSUE THREAD

**Issue by timgivois** [EasyGraphQL/easygraphql-tester#68]
when using AWS Scalars like `AWSURL` the test doesn't pass

**Comment by estrada9166** [comment]
@timgivois Thanks for creating the issue! Can you share me the query/mutation you're doing, the error that it returns and if it's possible the schema, so I can try it locally!

Thanks!

**Comment by timgivois** [comment]
sure:

// schema.graphl
```
type User {
    id: ID!
    username: AWSEmail!
    image: AWSURL
}

type Query {
    users: [User]!
}
```

// schema.test.js

```
import fs from 'fs'
import EasyGraphQLTester from 'easygraphql-tester'

describe('Graphql Server', () => {
    beforeAll(() => {
        const schema = fs.readFileSync('schema.graphql', 'utf8')
        tester = new EasyGraphQLTester([schema, AWSScalar])
    })
    it('returns users', () => {
        const query = `
          query {
            users {
                id,
                email,
                image
             }
           }
        `
        tester.test(true, query)
    })
})
```

And the error is: 
```
    >      |     tester = new EasyGraphQLTester(schema)
            |                    ^
    Type "AWSURL" not found in document.
```

**Comment by timgivois** [comment]
Link to AppSync Scalars: https://docs.aws.amazon.com/appsync/latest/devguide/scalars.html

**Comment by estrada9166** [comment]
Can you try adding `scalar AWSURL ` on your schema, please!

The reason for this error is because the `scalar` definition is not found in the schema.

**Comment by timgivois** [comment]
yes, I created the scalars in a separate file that I'll import just for testing. I believe that this could be added to the library. I can create the PR for it ;)

**Comment by estrada9166** [comment]
That will be awesome!! Thanks!

Also, quick question... the separate file with the scalars is a `.graphql` file? in case that yes, you can do  `tester = new EasyGraphQLTester([schema, scalars])`

**Comment by estrada9166** [comment]
That's great!! does it work as expected?

**Comment by timgivois** [comment]
Yes it works as expected @estrada9166 :)

**Comment by estrada9166** [comment]
@timgivois Can we close this issue?

**Comment by estrada9166** [comment]
@timgivois Would you like to create a PR? I can tell you how it'll be solved! or I can push the changes if you want!

**Comment by timgivois** [comment]
well, I saw that `validator.js` doesn't take into account scalars. I'm not sure what could be the best way to modify that line of code: if we saw that we receive a String and it has a scalar type it should pass, right?

**Comment by timgivois** [comment]
Thanks, that will be great. @estrada9166

**Comment by estrada9166** [comment]
That awesome!! We need to do multiple things!

#### How to do it?
+ We should validate if the argument is `scalar`, so, we have the parsed schema (`schema`) and each argument has a `type` property (will be the nested type), so we can search for that `type` on the schema, if there is one check the type if it's 
`'ScalarTypeDefinition'` so if it's it means that `isScalar = true`
  + This should be done [here](https://github.com/EasyGraphQL/easygraphql-tester/blob/master/utils/validator.js#L241) and [here](https://github.com/EasyGraphQL/easygraphql-tester/blob/master/utils/validator.js#L244) and pass the value to `validateInputArg()` as last argument... we should remove that `true`

+ Now on `validateInputArg` we have to do multiple things:
  + `filteredArg` can be `undefined` but sometimes it should not be that because `schemaVar` can be an object but it doesn't mean is a nested object that we can access like `schemaVar[arg.name]`, so we should validate if `filteredArg` is undefined, lets check if it's an object that contains `kind` and use `getArgValue(schemaVar)` to get the argument value... when is this happening? [This](https://github.com/EasyGraphQL/easygraphql-tester/blob/master/test/tester.js#L246) is the case
  + We should remove `isScalar` from [here](https://github.com/EasyGraphQL/easygraphql-tester/blob/master/utils/validator.js#L255) because, now if it's `undefined` is because that argument is missing
  + The last thing is to validate is `isScalar` before validating the [`typeof`](https://github.com/EasyGraphQL/easygraphql-tester/blob/master/utils/validator.js#L270) of the argument, so if it's a `scalar` we should return

I tried to explain with the more details possible, but if can help you with more details or something else, it'll be a pleasure for me :)!!

**Comment by timgivois** [comment]
Sure @estrada9166, I'll dive into the code this days. If anything comes up I'll directly reach you!
